### ISSUE TITLE
build transforms this to undefined

### ISSUE THREAD

**Issue by lifeiscontent** [alexjoverm/typescript-library-starter#112]
Hey there, I've got a project which extends a few typescript classes and the build output transforms `this && this.__extends` to `undefind && undefined.__extends` any ideas how to fix this so classes work properly?

**Comment by alexjoverm** [comment]
Could you provide a reproducible example that I can check?

**Comment by lifeiscontent** [comment]
@alexjoverm adding

`"importHelpers": true,`
to tsconfig.json fixed it

**Comment by alexjoverm** [comment]
That's weird. That setting shouldn't be related to the scope of `this`.

Do you have an example that I can check?

**Comment by lifeiscontent** [comment]
@alexjoverm I think you might be right. I'll open the issue again if I have some time to further investigate.
