### ISSUE TITLE
Cannot find module '../../package' from 'node.js'

### ISSUE THREAD

**Issue by pyramation** [alexjoverm/typescript-library-starter#115]
Not sure if this is a bug related to this package or typescript, but I isolated it and was able to get it to work in plain JS.

Here's the bug:
 
```
Cannot find module '../../package' from 'node.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/babel-core/lib/api/node.js:60:16)
```

For reproducibility, I've built out an example that includes both a success (using plain js) and a failure test (using the typescript test)

https://github.com/pyramation/typescript-starter-example

**Comment by alexjoverm** [comment]
Seems to be an issue in babel-core. I've [opened a PR](https://github.com/babel/babel/pull/6524), so you can keep track in there.
