### ISSUE TITLE
Add AndreaGot to contributors

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#119]
[AndreaGot](https://github.com/alexjoverm/typescript-library-starter/commits?author=AndreaGot) contributed to this repo but hasn't been added to contributors yet.

Follow up #92 to see instructions

**Comment by Yogendra0Sharma** [comment]
@alexjoverm i am working on it.

**Comment by alexjoverm** [comment]
Closed by #123
