### ISSUE TITLE
Projects created with typescript-library-starter README section?

### ISSUE THREAD

**Issue by lifenautjoe** [alexjoverm/typescript-library-starter#132]
You guys are rocking it and I am sure my library is not the only library using your starter. 

It would be great if people could know this when they come to the project, so they get an extra confidence boost on using the starter.

Is it an idea to add a `Projects created with typescript-library-starter` section in the README? 

My library is [Noel](https://github.com/lifenautjoe/noel) (it also got featured this week on the JavaScript weekly newsletter).

**Comment by alexjoverm** [comment]
Hi @lifenautjoe!

Sure! That sounds like a great idea indeed! Do you mind creating a PR on the Readme for it?
