### ISSUE TITLE
coveralls not reporting

### ISSUE THREAD

**Issue by lifeiscontent** [alexjoverm/typescript-library-starter#140]
Hey @alexjoverm,

do you mind taking a look at this? I can't seem to get coveralls to work with typescript-library-starter

here's the build: https://travis-ci.org/lifeiscontent/react-mutate-icon
here's the code: https://github.com/lifeiscontent/react-mutate-icon

thanks!

**Comment by alexjoverm** [comment]
It seems like the build is passing and I see no issues with coverage itself. Probably the issue is in the side of Coveralls. Have you synced up the repo correctly in there?

**Comment by lifeiscontent** [comment]
@alexjoverm seems to be working now. I think coveralls servers are grinding to a halt.
