### ISSUE TITLE
type definitions not generated if atl useCache

### ISSUE THREAD

**Issue by mkel** [alexjoverm/typescript-library-starter#16]
The current version only generates type definitions on first run if awesomeTypescriptLoaderOption useCache is true (as it is after npm install). The subsequent runs don't generate type definitions.

Also, on the first run the type definitions are generated into dist/src/, not in the dist/types/ which is the typings location specified in package.json.

**Comment by alexjoverm** [comment]
Hi, thanks for the issue!

Hmm, I had also some problems with `useCache`. Then better let's remove it, it doesn't save too much time anyway ;)

About the types going to 'dist/src', true that. This could be related to changing from ts-loader to awesome-typescript-loader. It seems like somehow is ignoring the `outDir` property on `tsconfig.json`.

I've already removed useCache. I've just opened #18 for that.

PR or help for the other issue would be helpful 👍
