### ISSUE TITLE
Build breaks on axios

### ISSUE THREAD

**Issue by JuliusKoronci** [alexjoverm/typescript-library-starter#169]
If you have axios as dependency the build breaks. Rollup need also a json plugin to be able to parse package.json 

I added 
import json from 'rollup-plugin-json'
and enabled in the plugins
   json(),

I had this issues only with axios but than again it is a very common library

**Comment by alexjoverm** [comment]
Duplicated https://github.com/alexjoverm/typescript-library-starter/issues/76.

Although it might be a good idea to include it by default. In progres...
