### ISSUE TITLE
jest config broken

### ISSUE THREAD

**Issue by mkel** [alexjoverm/typescript-library-starter#17]
I can't find a way to instantiate the generated DummyClass in test case without errors. Runnin npm test results in

       ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){require('ts-jest').install();import DummyClass from "../src/liblib";
                                                                                                                          ^^^^^^
    SyntaxError: Unexpected token import

      at e (node_modules/jest-runtime/build/transform.js:320:12)

**Comment by mkel** [comment]
Tests did work fine with ts-loader version a few days ago. So this got broken with awesome-typescript-loader too.

**Comment by alexjoverm** [comment]
@mkel This is not related to awesome-typescript-loader at all. In fact, webpack has nothing to do with the Jest setup.

Found the issue, seems like ts-jest doesn't work when I removed `"module": "commonjs"` from `tsconfig.json` (needed for the tree-shaking).

So, for now I'll create a `tsconfig.test.json` to fix this and open an issue to ts-jest

Thanks for pointing out!

**Comment by alexjoverm** [comment]
Seems like setting the following adds that config to the tsconfig.json, and then it works:

```
"globals": {
  "__TS_CONFIG__": {
    "module": "commonjs"
  }
}
```

Opened anyway https://github.com/kulshekhar/ts-jest/issues/121
