### ISSUE TITLE
Compilation error on fresh install

### ISSUE THREAD

**Issue by mattmazzola** [alexjoverm/typescript-library-starter#172]
Description:
I followed the instructions to clone, run npm install, change directories, then I immediately ran `npm run build` to see the output and it failed.

```
npm run build

> ts-lib-starter-test-01@0.0.0 prebuild D:\repos\ts-lib-starter-test-01
> rimraf dist


> ts-lib-starter-test-01@0.0.0 build D:\repos\ts-lib-starter-test-01
> tsc --module commonjs --outDir dist/lib && rollup -c rollup.config.ts && typedoc --out dist/docs --target es6 --theme minimal --mode file src

node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.
```

See video:
http://recordit.co/2opsyFz3ln

I'm guessing part of lodash's definition file doesn't meet all the constraints checked by the latest version of TypeScript.

From looking at the package.json it specifies:
`"typescript": "^2.6.2",` an this resolved to `"2.7.1"` in lock file.

I manually re-ran `npm i -D typescript@2.6.2` and it seemed to fix the build; however, I shouldn't need to.

Maybe the package.json should be updated to have locked version of typescript which is known to work or at least restrict to 2.6.x

I'm not sure if people have strong preference over using approximate version or exact version for the fix:
`"typescript": "~2.6",`
`"typescript": "2.6.2",`

Or if someone knows more, maybe lodash has already published a new version compatible with 2.7.1

**Comment by mattmazzola** [comment]
Btws, I'm using:
Windows 10 (Version 10.0.16299 Build 16299)
npm: 5.5.1
node: v8.2.1

After some further investigation I see @types/lodash was pulled in for `typedoc`
And from running `npm view @types/lodash` it looks like the latest available is: 4.14.98

```
    "typedoc": {
      "version": "0.9.0", <----- Seems to be latest
      "resolved": "https://registry.npmjs.org/typedoc/-/typedoc-0.9.0.tgz",
      "integrity": "sha512-numP0CtcUK4I1Vssw6E1N/FjyJWpWqhLT4Zb7Gw3i7ca3ElnYh6z41Y/tcUhMsMYn6L8b67E/Fu4XYYKkNaLbA==",
      "dev": true,
      "requires": {
        "@types/fs-extra": "4.0.0",
        "@types/handlebars": "4.0.31",
        "@types/highlight.js": "9.1.8",
        "@types/lodash": "4.14.74",    <----- LODASH (Outdated, latest is 4.14.98)
```

I think the root issue would mean to open issue on Typedoc and get them to update their dependency on @types/lodash to latest version and publish new 0.9.1 version assuming that the latest version of @types/lodash is compatible with TypeScript 2.7.1

**Comment by mattmazzola** [comment]
Opened issue on Typedoc repo as well. I would assume it's better to update the package.json in this repo for time being until they get update?

**Comment by mattmazzola** [comment]
I'm kind of confused because when I downgrade the toplevel of typescript from 2.7.1 to fix the issue with @types/lodash which are from my understanding only a dependency of typedoc, it actually runs typedoc with it's local version of typescript 2.4.1 which should be compatible with that version of @types/lodash

> Using TypeScript 2.4.1 from D:\repos\ts-lib-starter-test-01\node_modules\typedoc\node_modules\typescript\lib

**Perhaps something in the build is messed up and first running typedoc with 2.7.1 and then re-running with 2.4.1?** 

```
D:\repos\ts-lib-starter-test-01 [master +16 ~0 -0 !]> npm i -D typescript@2.6.2
npm WARN rollup-plugin-typescript2@0.9.0 requires a peer of rollup@^0.50.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ typescript@2.6.2
added 116 packages and updated 1 package in 9.56s
D:\repos\ts-lib-starter-test-01 [master +16 ~0 -0 !]> npm run build

> ts-lib-starter-test-01@0.0.0 prebuild D:\repos\ts-lib-starter-test-01
> rimraf dist


> ts-lib-starter-test-01@0.0.0 build D:\repos\ts-lib-starter-test-01
> tsc --module commonjs --outDir dist/lib && rollup -c rollup.config.ts && typedoc --out dist/docs --target es6 --theme minimal --mode file src

(!) Some options have been renamed
https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32
sourcemap is now output.sourcemap

src/ts-lib-starter-test-01.ts → dist/ts-lib-starter-test-01.umd.js, dist/ts-lib-starter-test-01.es5.js...
created dist/ts-lib-starter-test-01.umd.js, dist/ts-lib-starter-test-01.es5.js in 869ms

Using TypeScript 2.4.1 from D:\repos\ts-lib-starter-test-01\node_modules\typedoc\node_modules\typescript\lib
Rendering [========================================] 100%

Documentation generated at D:\repos\ts-lib-starter-test-01\dist\docs
```

**Comment by alexjoverm** [comment]
According to https://github.com/TypeStrong/typedoc/issues/688#issuecomment-362321356 already on version 0.10.0. However, I've just tried but had no luck :(.

**Comment by alexjoverm** [comment]
After updating depending, everything is back to normal. Fresh installs work again \o/
