### ISSUE TITLE
Discussion about package size

### ISSUE THREAD

**Issue by mattmazzola** [alexjoverm/typescript-library-starter#177]
I recently came across issue where I'm trying publish packages to a proxy repository (not the official NPM) and this particular repository server has a default max body limit I believe 1 MB and was rejecting my `npm publish` requests for my package created using typescript-library-starter.

At first I thought the custom repo just had bugs; however, I did some investigation and realized the packages are actually massive produced by these are massive. They included 3 different copies of the code in different compile targets and docs.

This is kind of related to my other issue / questions here: #176 but I hope this is more specific.  Since I don't understand history of these configuration decisions it's hard to say, but as of now it looks like we should reduce the size dramatically by only publishing the final build output and not the other 3 versions.

I would say my library is avarage size and yet after running `npm pack` and looking at **the compressed tgz file it was still 7 MB.  The uncompressed .tar file was 20 MB**

In the `/dist` filder there is:

```
dist/ (All the .d.ts files, plus the merged .es5.js and .umd.js files) ~ 174 KB 
dist/es (The separated es5 files) 60 KB
dist/lib (The commonjs files) 60 KB
dist/types (The .d.ts files) 40 KB
dist/docs (Typedocs) 20 MB!
```

I don't agree with having the docs in the package.  Every time someone has to install our package they have to download 20 MB of documentation they will likely never look at. 

There could be argument that when docs are included in the package they guarantee version consistency, but this could also be done by not - force pushing to gh-page and versioning each commit then linking to the correct version.

The easy way would be for me to simply remove the `typedoc` part of the build command:
`typedoc --out dist/docs --target es6 --theme minimal --mode file src`

However, the `deploy-docs` script relies on the docs being in dist/docs.

## Proposal
In order to move forward on this I think we need answer to my other issue about why we need 3 different versions of the same code in the dist folder.  As far as I understand the only think that matters is the files in the dist root.

- [ ] Move generation of docs from npm build to deploy-docs and dont put them in dist folder (perhaps docs)
- [ ] Update gh-pages-publish script to look for docs in new location
- [ ] Remove duplicate builds of library before publishing /dist/es /dist/lib /dist/types

**Comment by mattmazzola** [comment]
I noticed that the readme says:

> Additionally, you can import the transpiled modules from dist/es in case you have a modular library:
> ```
> import something from 'mylib/dist/es/something'
> ```

However, from what i'm seeing, the `dist/es` directory is not generated on `npm run build` so this would not be in the distributed package. The `lib` folder is though, due to the `--outDir dist/lib`
Perhaps it was a typo, but this might give clue to the purpose of the extra `lib` directory.

**Comment by alexjoverm** [comment]
Hi @mattmazzola! Thanks for this feedback, is great!

It's crazy the typedoc files are that huge, indeed we should move it somewhere else and update the gh-pages-publish script, so your proposal looks good.

About the different kind of bundles, we should keep them: 
 - `dist/es`: There is the case where you want to publish a multi-module lib (think lodash) and this would be helpful. The discussion is on #134.
 - `dist/lib`: Same for cjs, although thinking about it I'm not sure if this is needed. But I guess for node environments it it.
 - `dist/types`: This is generated by typescript, they keep the same structure as the source. I looked in the past into how to tell typescript to merge them in one file, but it doesn't support it (maybe now it does?).

It seems to be an issue that rollup re-emits the types, we could open a different issue if that's the case.

**Comment by alexjoverm** [comment]
I don't have time lately to look into it, but feel free to send PR. Aside, if you'd like to be added as a collaborator, that'd be helpful indeed! You know pretty well the codebase and seem to be using it quite frequently :)

**Comment by alexjoverm** [comment]
@mattmazzola see https://github.com/alexjoverm/typescript-library-starter/issues/176#issuecomment-367304839. Closing issue.
