### ISSUE TITLE
Types are generated on dist/src instead of dist/types

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#18]
Relates to #16

**Comment by alexjoverm** [comment]
@mkel any ideas about this one?

**Comment by mkel** [comment]
I also noticed that it did work with ts-loader before but got broken when awesome-typescript-loader was introduced. I have not had time to figure out why.

**Comment by alexjoverm** [comment]
It seems like there are some issue from ATL end. For now fixed this by updating the path on `package.json`.

Opened #19 for future tracking of it.

**Comment by superamadeus** [comment]
I do believe #20 may solve this issue.
