### ISSUE TITLE
Uglified/Minified JS

### ISSUE THREAD

**Issue by cyphercodes** [alexjoverm/typescript-library-starter#191]
How to you produced uglified JS code from this?

Is there an option to allow generation of both JS files below on build:

`dist/lib/location-picker.js`
`dist/lib/location-picker.min.js`

**Comment by se-panfilov** [comment]
@cyphercodes Why this one closed? I think it'd be nice to have, no?
I mean - it's not so straightforward process imho

**Comment by se-panfilov** [comment]
@cyphercodes 

> In case you want to generate two files, one minified and one not, you need to export an array of two config objects.

That's exactly what I'm looking for. Thanks a lot
