### ISSUE TITLE
Semantic release pushing only package.json to npm

### ISSUE THREAD

**Issue by maxime1992** [alexjoverm/typescript-library-starter#198]
Hi

Everything is working on Travis, testing, building, release new version on GIthub... BUT:

The released package on NPM only has `package.json` and `README`.

I'm not sure if it's a configuration that I'm missing in typescript-library-starter, a bug in semantic-release... Or probably just me missing something! But it's definitely driving me crazy and I can't figure out why my package is not correctly deployed to NPM.

So I tried to do some debug on Travis and I've added `ls -a` right before the `yarn run semantic-release`.

The result is normal:
```
$ ls -a
.
..
bin
coverage
.editorconfig
.git
.gitignore
node_modules
.nojekyll
package.json
README.md
rollup.config.ts
.rpt2_cache
src
tools
.travis.yml
tsconfig.json
tslint.json
yarn.lock
```

So all my files are here and my `.gitignore` contains the following: 
```
node_modules
coverage
.nyc_output
.DS_Store
*.log
.vscode
.idea
dist
compiled
.awcache
.rpt2_cache
```

The folder supposed to be deployed is `bin`. So as long as I have my `package.json` and the bin folder it should be ok (it's a global package, thus the `bin`...).

You can take a look into Travis logs here: https://travis-ci.org/maxime1992/pulse-issues

If you want to see the code, it's all on Github here: https://github.com/maxime1992/pulse-issues

Thanks for any help on that :+1: and congrats for this starter which is really nice :smile:!

**Comment by alexjoverm** [comment]
By default, as you can see in the package.json https://github.com/alexjoverm/typescript-library-starter/blob/master/package.json#L10, the `dist` folder is the one published. Whatever you need to be published, you'll need to include it in `files` property.

**Comment by maxime1992** [comment]
**Thank you** :pray:, completely missed that part...
