### ISSUE TITLE
semantic-release and package.json version

### ISSUE THREAD

**Issue by Neoflash1979** [alexjoverm/typescript-library-starter#207]
Just started using this repo and I love it. Everything works like a charm, including automatic releases to Travis CI, coveralls, github and npm. I have noticed however that the package.json 's `version` field seems to be stuck at `0.0.0-development` even though semantic-release seems to have pushed version 1.0.0 to NPM. Is it not also supposed to modifiy the package.json version field? Am I doing something wrong? Thanks for the help and the great work on this repo.

**Comment by alexjoverm** [comment]
Hi @Neoflash1979, that's how semantic release works ;). Refer to its documentation for more info

**Comment by Neoflash1979** [comment]
See issue #208 for my fix.
