### ISSUE TITLE
No changelog

### ISSUE THREAD

**Issue by Neoflash1979** [alexjoverm/typescript-library-starter#208]
I don't know if I'm doing something wrong but I was under the impression that somewhere between `npm run commit` and `git push` a changelog was supposed to be generated. Is that not the case? It's not doing it for me.

**Comment by alexjoverm** [comment]
Not exactly, that happens automatically by semantic release and will end up on github's releases

**Comment by Neoflash1979** [comment]
Turns out that by default, semantic-release doesn't generate a changelog file. Adding the following to my package.json has made what I wanted possible:

```
"release": {
    "verifyConditions": [
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/github",
      "@semantic-release/git"
    ],
    "prepare": [
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/git"
    ]
  },
```

**Comment by alexjoverm** [comment]
Hmm, that used to happen automatically, so probably that changed on some major version.

@kutyel have you verified this?
