### ISSUE TITLE
test coverage for all files

### ISSUE THREAD

**Issue by MikBin** [alexjoverm/typescript-library-starter#236]
Hi,
not really an issue, just a suggestion for improvement:
 I've added the following  
```
"collectCoverageFrom": [
      "src/*.{js,ts}"
    ]
```
 in package.json under "jest":{} (configuration)
this way all files under ./src directory are covered
I hope this could be of some help

**Comment by alexjoverm** [comment]
Hi @MikBin, that's great! Do you mind opening a PR with the change? :)

**Comment by MikBin** [comment]
PR done. thanks

**Comment by alexjoverm** [comment]
Closed by #246
