### ISSUE TITLE
npm ci is erroring out on travis

### ISSUE THREAD

**Issue by johnstonmatt** [alexjoverm/typescript-library-starter#238]
[this build](https://travis-ci.org/johnstonmatt/easy-e/builds/420778176) and a few others failed to test while everything is making it through  `npm run commit`
builds would take >30mins in queue if I deleted the cache in travis' ui
setting cache to false in .travis.yml seemed to resolve it

**Comment by johnstonmatt** [comment]
was this resolved?

**Comment by alexjoverm** [comment]
@johnstonmatt your error has nothing to do with this library

**Comment by johnstonmatt** [comment]
Oh sorry I wrote that when I didn't understand the architecture and didn't
think too hard about it after, thanks for letting me know and sorry about
the clutter!
