### ISSUE TITLE
Install of semantic-release fails on Windows 10

### ISSUE THREAD

**Issue by mattmazzola** [alexjoverm/typescript-library-starter#25]
This isn't really issue for this repo but for semantic-release and I opened issue there:
https://github.com/semantic-release/semantic-release/issues/372

But I assume since this repo is targeted twoards TypeScript  devs this is more likely to be people who use Microsoft / Windows and thought surely one of the maintainers has found a solution?

If there's no known work-around then maybe just add a warning to that section of the README explaining that you can't really use the semantic-release features of the starter kit if you're on Windows and close this issue.

**Comment by alexjoverm** [comment]
Hey @mattmazzola,

Sorry to say the typical thing: "It works on my machine" 😄 true story. It's not really my machine, I use Mac, but tried with a friends computer. Although I've identified another small issue on this repo related to semantic release: a repository.url is needed in package.json.

Windows 10 home
Node: 7.7.4
Npm: 4.1.2

I'm closing this, let's see if in their repo they find your specific issue
