### ISSUE TITLE
How to exclude depending lib

### ISSUE THREAD

**Issue by hrajchert** [alexjoverm/typescript-library-starter#33]
Hi! 

Lets say I'm creating an RxJs operators lib. I add the lib as a dep in`package.json` but that includes rxjs inside the exported bundle.

What is the best way to exclude it from the bundle?

I've tried using the webpack ingnore plugin like this

```javascript
const plugins = [
  new CheckerPlugin(),
  new TsConfigPathsPlugin(),
  new webpack.IgnorePlugin(/rxjs/),
  new HtmlWebpackPlugin({
    inject: true,
    title: libraryName,
    filename: 'index.html',
    template: join(__dirname, 'template/index.html'),
    hash: true,
    chunks: ['common', 'index']
  })
]
```

but that replaces the includes with a `throw`

```javascript
/***/ }),
/* 42 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__maybe__ = __webpack_require__(20);
throw new Error("Cannot find module \"rxjs/Observable\"");
throw new Error("Cannot find module \"rxjs/add/observable/of\"");
```

Any help appreciated!

Thanks and continue the good work ;)

PS: Have you discussed using rollup instead of webpack for creating the bundle?

https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c

**Comment by alexjoverm** [comment]
Hi @hrajchert!

You can exclude external libraries by using the `externals` property on your webpack config. Take a look at [Authoring libraries in the official docs](https://webpack.js.org/guides/author-libraries/)

I've considered rollup. For now I'd rather use webpack as the official bundler, since it's more like a all-in-one solution, but I'm open if anyone wants to create a rollup version, in another branch or a fork ;)

**Comment by hrajchert** [comment]
The externals worked as a charm! But quick follow up, the `npm run build` minifies the library while `rpm run build:dev` adds a ton of overhead regarding Hot Module replacement. 

I've checked the webpack config and found where the library is being added but I couldn't find where do you say to minify the output.

Normally when you are creating a library you want to have the exported bundle and optionally the minified version.

Cheers!
