### ISSUE TITLE
Setup different bundles

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#35]
@hrajchert suggested in #33 to use RollupJS instead of Webpack. After reading the following articles, it seems (by the date of April 2017) RollupJS fits better for library usage:
 - [The cost of small modules](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/)
 - [Webpack and Rollup: the same but different](https://medium.com/webpack/webpack-and-rollup-the-same-but-different-a41ad427058c)

Axel Rauschmayer describes pretty well in the article ["Setting up multiplatform npm packages"](http://2ality.com/2017/04/setting-up-multi-platform-packages.html) what we can use as a standard convention for providing different bundles in npm packages. 

Jason Aden does it as well in a talk in the ngconf talk ["Packaging Angular libraries"](https://www.youtube.com/watch?v=unICbsPGFIA)

**Comment by hrajchert** [comment]
Haven't seen the talk yet but I will

Thanks for the quick response :)

**Comment by alexjoverm** [comment]
Closed by 75dd59b
