### ISSUE TITLE
npm install failing on bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by SteveALee** [alexjoverm/typescript-library-starter#37]
It looks like the run of the post install script fails with the following. At least I never get prompted for the library name

````bash
> spawn-sync@1.0.15 postinstall /mnt/c/projects/spikes/typescript-library-starter/node_modules/spawn-sync
> node postinstall

npm WARN lifecycle --libraryname--@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) --libraryname--@0.0.0 node tools/init /mnt/c/projects/spikes/typescript-library-starter
--libraryname--@0.0.0 /mnt/c/projects/spikes/typescript-library-starter
```

**Comment by SteveALee** [comment]
I've no idea why spawn-sync is being used but a simple fix is to manually run

```npm run postinstall```

**Comment by SteveALee** [comment]
Closing as is an issue for WSL not this project

**Comment by alexjoverm** [comment]
Thanks for the info Steve! Is there something we can do from our side to prevent failing on that situation?

I suppose that package is a "dependency of a dependency"

**Comment by SteveALee** [comment]
@alexjoverm Only not calling "npm script" from a script but that is a standard pattern so you would be working around a bug in a tool/platform combination. I would hope MS fix it as npm is common dev tool and supporting devs is what WSL is all about!
