### ISSUE TITLE
Gh-pages-publish repository parameter

### ISSUE THREAD

**Issue by Leefrost** [alexjoverm/typescript-library-starter#39]
Hi,
I got a problem when I tested some features of library-starter.  Problem is in this line in file tools/gh-page-publish.js:

`let repository = url.parse(pkg.repository)`

But config file contains a little bit different node:

`  "repository": {
    "type": "git",
    "url": "https://someurlhere.git"
  }`

So maybe we should parse **pkg.repository.url**? Or i miss something during installation process :(

**Comment by alexjoverm** [comment]
Hi @Leefrost, you're totally right about this!

A good thing, could be to check whether `pkg.repository` is a string or an object, since the `repository` key can be written in a shorthand way (just the string).

Would you be able to make a PR for this?

**Comment by Leefrost** [comment]
Hi @alexjoverm! Here is my pull request

**Comment by alexjoverm** [comment]
Closed as per #44, thanks a lot!
