### ISSUE TITLE
Concider adding "externals" to the webpack config to shrink the bundle by removing dependencies

### ISSUE THREAD

**Issue by SteveALee** [alexjoverm/typescript-library-starter#41]
(continued from #38)

As it stand the generated <library>.js includes all dependencies.

It rather depends on usage but I think this is incorrect

If the consuming code includes several libraries that are built with this starter and have common dependencies a duplication is likely to occur in the global (root) namespace.

Better the dependencies at left for the user to figure out - though this strays into the pain of manual dependency management

> Already had a question about this #33. I thought you must specify which libraries to exclude, so in the end the user has to know about that and include it by themselves on the externals and the peerDependencies in the package.json.

Externals only drops stuff from the generated bundle.js - so adding to package.json will make no difference. They need to be added in the code that includes the library script.

But yes this could be a right royal pain as noted above.

Another problem with `externals` is you seem to need to [declare the module schemes](https://webpack.js.org/configuration/externals/) and that would be a pain to manage.

**Comment by alexjoverm** [comment]
As we discussed on #38, there is no automatic way to exclude external dependencies, either in Rollup or Webpack. Check their docs for more info. So there is nothing we can do here.

But we can mention that in the docs, so we point out to the users how to do it. Opened #45 for that

**Comment by alexjoverm** [comment]
Woho! I've just found https://www.npmjs.com/package/webpack-node-externals which can make this happen automatically, I'll give it a try!
