### ISSUE TITLE
Maybe add a note on https://unpkg.com

### ISSUE THREAD

**Issue by SteveALee** [alexjoverm/typescript-library-starter#42]
This comes with no SLAs etc but is an easy way to get a library onto a CDN

https://unpkg.com

**Comment by alexjoverm** [comment]
Hi @SteveALee,

What do you mean? I don't understand the purpose of this issue. If you use the automatic releases configured in this project, you get you UMD bundle on npm and thus it would be available on unpkg

**Comment by SteveALee** [comment]
Not every one knows about it so I thought a note in the readme would be helpful. Minor point so closing
