### ISSUE TITLE
Separate frontend-only stuff in another branch

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#46]
As discussed in #38, having HRM, dev-server and all that stuff confuses people thinking this starter is for frontend libraries, but it is universal since you can use it for both.

Let's separate that stuff in a different branch. Things to do:

 - Move HRM and all that stuff made on #22 to the frontend branch
 - Config the `environment` config of jest to `node` for the default (backend) branch
 - Add some docs at the begining pointing out the existence of these 2 versions

**Comment by SteveALee** [comment]
An alternative is to leave it in main branch as an option but:

* Put frontend config in a separate webpack config file
* use a npm script like "serve": "webpack --config fontend.config.js"

If you want to be DRY you could include one config file in another and possibly use object.assign() to alter it.

**Comment by alexjoverm** [comment]
Closing this by 75dd59b.

I didn't see very much the value of HRM for library development. Makes more sense to TDD or watch mode bundling.

I've added a `npm start` command though for watch mode compiling/bundling on changes. If the users want this we can go on and make it in another branch
