### ISSUE TITLE
[Possible Bug] Jest picks up test outside the test folder

### ISSUE THREAD

**Issue by Akkusativobjekt** [alexjoverm/typescript-library-starter#51]
I experimented a bit with the dependencies and renamed my `node_modules` folder and then noticed that jest tried to run the tests in the renamed `node_modules` folder, because it does not match the `coveragePathIgnorePatterns` anymore.

I for myself found this behavior somewhat unexpected and inconsistent, because I would expect that if there is a test folder, only this folder would be recognized by jest. A solution would possibly be the usage  of [collectCoverageFrom](https://facebook.github.io/jest/docs/configuration.html#collectcoveragefrom-array) and explicitly declaring the test folder.

If this is instead expected behavior, then everything is fine :stuck_out_tongue_winking_eye:

**Comment by alexjoverm** [comment]
Hi @Akkusativobjekt, sorry for the late response.

It is indeed expected behaviour! There are mainly 2 ways of organising tests: 

 - Under a test folder
 - Within the source code, as `*.test.ts`

Jest contemplates both cases, and I'm very happy about it ;)
