### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by alexandru** [alexjoverm/typescript-library-starter#52]
On running the test command I'm getting the following warnings:

```
(node:73480) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: require(...) is not a function
(node:73480) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is on a fresh clone of `typescript-library-starter`. Any idea of how to fix?

PS: this project template is really useful, thanks!

**Comment by k1r0s** [comment]
There were some old configurations that are no longer required and output some warnings
