### ISSUE TITLE
Forgot to remove `.babelrc`?

### ISSUE THREAD

**Issue by jazen** [alexjoverm/typescript-library-starter#56]
Should have been done with b469c83543edeb3af2, I guess. Nice setup though!

**Comment by alexjoverm** [comment]
True. I removed Babel for simplicity, since I realized for libraries you normally don't have a lot of setup. Plus core-js covers the case better by adding just the needed polyfills in most cases.

Closed by 31d4e28d7bcb9fb7bf034c52b4d0d33f2534e522
