### ISSUE TITLE
Fixed git information on gh-pages-publish

### ISSUE THREAD

**Issue by durancristhian** [alexjoverm/typescript-library-starter#68]
Hi, I've started to use the `typescript-library-starter` and I saw that in this line https://github.com/alexjoverm/typescript-library-starter/blob/master/tools/gh-pages-publish.ts#L25 the git information is hard-coded. I'm pretty sure that this can be solved in a better way and I wanted to notify you guys about it.

I'll see if I'm able to send a PR fixing this :)

**Comment by alexjoverm** [comment]
I must have commited that accidentally sometime :O
