### ISSUE TITLE
Unable to debug Jest tests using VSCode

### ISSUE THREAD

**Issue by marcantoineveilleux** [alexjoverm/typescript-library-starter#73]
With the default project, I am unable to set breakpoint in visual studio code.

Here's my _launch.json_:
```
{
  // http://markuseliasson.se/article/debugging-jest-code/
    "version": "0.2.0",
    "configurations": [
        {
          "name":"Jest Tests",
          "type":"node",
          "request":"launch",
          "program":"${workspaceRoot}/node_modules/jest-cli/bin/jest.js",
          "stopOnEntry":false,
          "args":[
              "--runInBand"
          ],
          "cwd":"${workspaceRoot}",
          "preLaunchTask":null,
          "runtimeArgs":[
              "--nolazy"
          ],
          "env":{
              "NODE_ENV":"development"
          },
          "console":"integratedTerminal",
          "sourceMaps":false
        }
    ]
}
```

**Comment by alexjoverm** [comment]
Hi @marcantoineveilleux. I'm sorry but I don't think this issue belongs to this repository.

If you can set breakpoints with ts-jest, you should be able to do it here. So I suggest better ask in stackoverflow about it ot open an issue in ts-jest.

Nonetheless, I'll keep this issue open some days in case someone knows the answer

**Comment by mattmazzola** [comment]
I had opened similar issues on VSCode and Jest repos.
Two things, it only works with legacy protocol (not inspect), and it does not work with Node 7 or 8 due to breaking changes in the vmContext stuff.

Root Issue:
https://github.com/nodejs/node/issues/7593

See related issues:
https://github.com/Microsoft/vscode/issues/28007
https://github.com/facebook/jest/issues/3748

**Comment by tonysneed** [comment]
@mattmazzola This launch.json file works for me.  I'm able to set breakpoints and hit them.

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Tests",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/jest/bin/jest.js",
      "sourceMaps": true,
      "runtimeArgs": [
        "-i"
      ],
      "env": {
        "NODE_ENV": "development"
      },
      "outFiles": [
        "${workspaceRoot}/dist/**/*"
      ],
      "cwd": "${workspaceRoot}"
    }
  ]
}
```

The weird thing is that I have to press F5 twice, because the first time the debugger exits without hitting the breakpoint.  But it hits the breakpoint the second time through. 😄
