### ISSUE TITLE
'Unexpected token` when running rollup with axios

### ISSUE THREAD

**Issue by NicklasWallgren** [alexjoverm/typescript-library-starter#76]
Im getting the following error when running `npm run start` with the default rollup.config.js.

```
Error: Unexpected token
node_modules/axios/package.json (2:9)
1: {
2:   "_from": "axios@^0.16.2",
```

**Comment by alexjoverm** [comment]
Hi @NicklasWallgren,

Is somehow weird, but axios node adapter requires its own `package.json` which rollup doesn't understand by default.

To make rollup understand json files, just use [rollup-plugin-json](https://github.com/rollup/rollup-plugin-json). I've just tried and it's working fine.

**Comment by maxime1992** [comment]
Lost so much time on this one, maybe you should consider to add the plugin by default @alexjoverm ?

It was not working without that for a table module and now with https://github.com/sindresorhus/ora

I've just added 


`import json from 'rollup-plugin-json'`

and `json(),` within the `plugins` array and it's fine now.

**Comment by alexjoverm** [comment]
That sounds like a good plan @maxime1992. Would you mind sending a PR? It should be easy :)

**Comment by maxime1992** [comment]
I'll try to do that this evening :)

**Comment by maxime1992** [comment]
@alexjoverm done ;)

**Comment by SumNeuron** [comment]
@maxime1992 

```
Error: 'default' is not exported by node_modules/axios/index.js

https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-
https://rollupjs.org/guide/en#error-name-is-not-exported-by-module-

1: import axios from 'axios'
          ^
2: 
3: const api = axios.create({


```
