### ISSUE TITLE
Compiling multiple typescript files

### ISSUE THREAD

**Issue by series0ne** [alexjoverm/typescript-library-starter#83]
This starter works great when your library has only one TypeScript file, but not to well it you have > 1 file. Would it be possible to configure the build process to build everything in a folder rather than a single? file

Source...
```
src
    \foo
        \bar.ts
        \baz.ts
```
...should produce...
```
\dist
    \compiled
        \foo
            \bar.js
            \baz.js
```

**Comment by tonysneed** [comment]
@series0ne [Rollup](https://rollupjs.org/) does the job of bundling for the starter kit, so whatever folder structure you have, it produces just one bundle.  For it all to work, you need to export each of your classes, then have one file with the same name as the project that exports all of them.  For example, with two exported classes, `HelloWorld` and `ItalianHelloWorld`, you need a ts file with the same name as your project that has the following:

```js
export { HelloWorld } from './hello/hello-world';
export { ItalianHelloWorld } from './hello/italian-hello-world';
```

Then rollup produces one js file with the two classes and has this at the bottom: `export { HelloWorld, ItalianHelloWorld };`

Hope this helps!

**Comment by alexjoverm** [comment]
@tonysneed said it clearly, that's the way to go for lib/app dev

**Comment by nareshbhatia** [comment]
I have a naive followup question - what's the point of the bundler when working on libraries? Isn't it something that only the "end-product" needs to do, e.g. a web-app that must be deployed? My current requirements are to have maybe 5-10 classes in a library. I simply use `tsc` to compile and throw them in the `dist` directory (including type definitions), set up the dependencies/peer dependencies correctly in `package.json` and everything seems to work fine. I am not seeing the reason for bundling dependencies along with a library. Isn't this something the final client should worry about? Again this may be a very naive question - just looking for the correct use case for bundling!

**Comment by alexjoverm** [comment]
There are several ways a lib can be used, and having a bundled one-file app in UMD format works universally, and needed for example if you use the lib from a CDN.

**Comment by nareshbhatia** [comment]
@alexjoverm, makes sense. Thanks for the clarification.
