### ISSUE TITLE
a branch to go with the egghead tutorial

### ISSUE THREAD

**Issue by lmj0011** [alexjoverm/typescript-library-starter#84]
There's a [tutorial] for this repo on egghead.io, however, there's not a branch that matches the project setup that the author starts off with in the videos.

Could we get this, please?

[tutorial]: https://egghead.io/courses/use-typescript-to-develop-vue-js-web-applications

**Comment by alexjoverm** [comment]
Hi,

The tutorial refers to the repo [Egghead-Typescript-Vuejs-apps](https://github.com/alexjoverm/Egghead-Typescript-Vuejs-apps). Probably you got confused
