### ISSUE TITLE
Add davidkpiano to contributors section

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#92]
This project uses the [all-contributors](https://github.com/kentcdodds/all-contributors) specifications. A very simple way to do this is using the [all-contributors-cli](https://www.npmjs.com/package/all-contributors-cli).

This PR can be achieved by running:

```
all-contributors add davidkpiano tool
```

And of course, add yourself as a contributor as well!

**Comment by aarongarciah** [comment]
I'll do it 😄

**Comment by aarongarciah** [comment]
PR done #98
