### ISSUE TITLE
Improve Readme grammar and docs

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#93]
Improve use of english and grammar in the README file, or just any improvement that can be made in the docs.

Examples:
 - Remove final dot from the list items that have it
 - Add links to the words github and npm
 - In the npm scripts section, some items have say Run and other Runs. Keep one.
 - ...

**Comment by gupta-meghna64** [comment]
I'd like to work on this :-)

**Comment by alexjoverm** [comment]
Partly done in #96, waiting for #99.

**Comment by alexjoverm** [comment]
Closed by #99
