### ISSUE TITLE
Add a Resources section with links

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#94]
I've got a couple of tutorial links:

 - https://dev.to/alexjoverm/write-a-library-using-typescript-library-starter
 - https://egghead.io/lessons/typescript-create-a-typescript-library-using-typescript-library-starter

Tony Sneed wrote an article about how he created a fork of this starter, mentioning it: 
 - https://blog.tonysneed.com/2017/09/15/introducing-typescript-library-starter-lite/

But any other resource related to this library is more than welcome!

**Comment by aarongarciah** [comment]
I'll do it 😄

**Comment by aarongarciah** [comment]
Do you want this section before or after the Credits one in the README.md file?

**Comment by aarongarciah** [comment]
PR done #101
