### ISSUE TITLE
Make more concise updated files log

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#95]
After downloading the starter and running `npm i`, the updated files log is very verbose due to printing the whole path:

![image](https://user-images.githubusercontent.com/5701162/31073247-697bf664-a76b-11e7-9ff6-266c30315d0e.png)

The code related to this is in [tools/init](https://github.com/alexjoverm/typescript-library-starter/blob/master/tools/init.ts#L46). Also, The removed files have a different order and color. It'd be nice to make this a bit more consistent

**Comment by stuajnht** [comment]
Hi,

I'm happy to have a look at this if no-one else has been assigned to it yet.

**Comment by alexjoverm** [comment]
Go ahead!

**Comment by alexjoverm** [comment]
Closed by #108
