### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/typescript-library-starter#97]
Aside from the usual stuff, is worth mentioning:

 - When you run `npm install` in this project, the git repo and files are changed. Be aware not to commit those changes. A good way is to create a copy of the repo and execute in that one the `npm install` while keeping the other for the changes

You can find info about good practise to write it in [Github open source guide](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)

**Comment by AndreaGot** [comment]
I'd like to work on this

**Comment by AndreaGot** [comment]
Pull request done, let me know if it is enough for you

**Comment by alexjoverm** [comment]
Closed by #100
